### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when deserializing MovePlayer packet

### ISSUE THREAD

**Issue by hach-que** [NukkitX/Protocol#8]
This is the stacktrace:

```
ERROR 2019-07-06 00:48:49,962 [Network Listener - #2][RakNetClient.java:167] : An exception occurred in RakNet
java.lang.ArrayIndexOutOfBoundsException: 1737435248
        at com.nukkitx.protocol.bedrock.v354.serializer.MovePlayerSerializer_v354.deserialize(MovePlayerSerializer_v354.java:42)
        at com.nukkitx.protocol.bedrock.v354.serializer.MovePlayerSerializer_v354.deserialize(MovePlayerSerializer_v354.java:14)
        at com.nukkitx.protocol.bedrock.BedrockPacketCodec.tryDecode(BedrockPacketCodec.java:54)
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:70)
        at com.nukkitx.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:17)
        at com.nukkitx.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:276)
        at com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:270)
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:398)
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:375)
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:363)
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:242)
        at com.nukkitx.network.raknet.RakNetClient$ClientDatagramHandler.channelRead(RakNetClient.java:151)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```

This is the code that crashes: https://github.com/NukkitX/Protocol/blob/44f16f1cf55ba8c314e9b19b5f477517838e5775/bedrock/bedrock-v354/src/main/java/com/nukkitx/protocol/bedrock/v354/serializer/MovePlayerSerializer_v354.java#L42

```
if (packet.getMode() == Mode.TELEPORT) {
            packet.setTeleportationCause(TeleportationCause.values()[buffer.readIntLE()]);
            packet.setUnknown0(buffer.readIntLE());
        }
```

Basically, the teleportation cause value is outside the supported values. In my case, the player is being teleported by a bot using commands.

It would be great if this could be gracefully handled with TeleportationCause set to `TeleportationCause.UNKNOWN`. At least if it's set to `UNKNOWN` then clients that don't care about this field (such as mine) can continue working even in the face of unknown teleportation causes.

**Comment by SupremeMortal** [comment]
Where did you receive this packet from? All the values in `TeleportationCause` are correct and anything outside this range is illegal.

**Comment by hach-que** [comment]
I got this packet from the Minecraft Bedrock dedicated server.

**Comment by SupremeMortal** [comment]
Closing due to inactivity
